# Numpy:

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

# Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important

# How to create rank 1 array:

NumPy is usually imported under the np alias.

alias: In Python alias are an alternate name for referring to the same thing.

In [29]:
#The version string is stored under __version__ attribute.
import numpy as np

print(np.__version__)

1.19.2


In [30]:
#Create numpy array
import numpy as np

In [31]:
an_array = np.array([3,33,333])   #create a rankk 1
print(type(an_array))             #the type of ndarray is "<calss.ndarray>"

<class 'numpy.ndarray'>


In [32]:
#test the shape of the array we just created, its should have one dimentional(rank1)
print(an_array.shape)

(3,)


In [33]:
#because this is a 1-rank, we need only one index to acces one element

print(an_array[0], an_array[1], an_array[2])

3 33 333


In [34]:
##ndarray are mutable,

an_array[0]=888
print(an_array)

[888  33 333]


In [35]:
an_array[2]=444
print(an_array)

[888  33 444]


# Representing matrises which will often usualy in data science

There are many way to create numpy arrays:


Here we create a number of different size arrays with different shapes and different pre-filled values. numpy has a number of built in methods which helps us quickly and easily create multi dimentional arrays.
    

In [36]:
another = np.array([[11,12,13], [21,22,23]])    #creat rank 2 array
print(another)   #print the array
print("The shape is 2 rows, 3 columnss:", another.shape)    #row X column
print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray:", another[0,0], ",", another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columnss: (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray: 11 , 21


In [37]:
#create 2x2 arrays of zero

ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [38]:
#create 2x2 arrays to filled with 9.0

ex2 = np.full((2,2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [39]:
#create 2x2 arrays with the diagonal 1s to the other 0

ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [40]:
# create an array of one

ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [41]:
#notice that the above ndarray(ex4) is actually rank2 it is a 2x1 array

print(ex4.shape)

#which means we needto use the two index to access an elenment
print()
print(ex4[0,1])

(1, 2)

1.0


In [42]:
#creat an array as an random floats between 0 and 1

ex5 = np.random.random((2,2))
print(ex5)

[[0.42763519 0.80493015]
 [0.65751506 0.59185419]]


# Array indexing:

In [43]:
ex6 = np.random.randint((2,2))
print(ex6)

[0 1]


# Slicing of array:

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [44]:
import numpy as np
#rank 2 arrayof shape(3,4)

an_array = np.array([[11,12,13,14], [21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get subrray consisting of the first 2rows x 2 columns

In [45]:
a_slice = an_array[0:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [46]:
#when you modify a slice, you actually modifying the underline array

print("Before:", an_array[0,1])  # inspect the element at 0, 1
a_slice[0,0] = 1000             #a_slice[0,0] is the same piece of the data as an_array[0,1]
print("After:", an_array[0,1])

Before: 12
After: 1000


Use both integer indexing and slice indexing
we can use combination of integer indexing and slice indexing  to creat different shaped matrises

In [47]:
#creat a rank 2 array of shape(3,4)

an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [48]:
#using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]       #rank 1 view
print(row_rank1, row_rank1.shape)   # notice only a single []

[21 22 23 24] (4,)


In [49]:
#slicing alone:generates an array of the same rank as the an_array

row_rank2 = an_array[1:2, :]    #rank 2 view
print(row_rank2, row_rank2.shape)  #

[[21 22 23 24]] (1, 4)


In [50]:
#we can do the same thing for columns of an array

print()
col_rank1 = an_array [:, 1]
col_rank2 = an_array [:, 1:2]
print(col_rank1, col_rank1.shape)  #rank1
print()
print(col_rank2, col_rank2.shape)  #rank2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [51]:
#create a new array
an_array =np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])
print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [52]:
#create an array of indices
col_indices =np.array([0,1,2,0])
print('\nCol indices picked:', col_indices)
row_indices = np.arange(4)
print('\nRows indices picked:', row_indices)


Col indices picked: [0 1 2 0]

Rows indices picked: [0 1 2 3]


In [53]:
#Examine the pairing of row_indices & column_indices. These are the elements we'll change next.

for row,col in zip (row_indices,col_indices):
    print(row,",",col)

0 , 0
1 , 1
2 , 2
3 , 0


In [54]:
#select one element from each row
print('Values in the array at those indices:',an_array[row_indices,col_indices])


Values in the array at those indices: [11 22 33 41]


In [55]:
#change oe element from each row using the indices selected

an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


# Boolean indexing:

In [56]:
import numpy as np

Array indexing for changing elements:

In [57]:
#create a array 3x2
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [58]:
#create a filter which wil be boolean values for wheather each element meets this condition
filter = (an_array>15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is same size ndarray as an_array which will filled  with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [59]:
#we can now select just those elements  which meets that criteria
print(an_array[filter])

[21 22 31 32]


In [60]:
#for short,we could have just used to approach below without the need for seperate filter array.
an_array[an_array >15]

array([21, 22, 31, 32])

What is particularly useful is that we can actually change elements in the arrayapplying a similar logical filter. let's add 100 to all the even values

In [61]:
an_array[an_array % 2 ==0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Data type:

The NumPy array object has a property called dtype that returns the data type of the array.



In [62]:
#python assing the data type
ex1 = np.array([11,12])
print(ex1.dtype)

int32


In [63]:
ex2 = np.array([11.1,12.7], dtype=np.int64)#
print(ex2.dtype)

int64


In [64]:
#you can also tell python the data type
ex3 = np.array([11,12], dtype=np.int64)
print(ex3.dtype)

int64


In [65]:
#you  can use this to force floats into integer (using  floor function)

ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [66]:
#u can use this to force integer into floats if u anticipate
#the values may changes ibnto floats later

ex5 = np.array([11,12], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 12.]


# Arithmatic array opertations:

In [67]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.]], dtype=np.float64)
print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222. ]]


Add:

In [68]:
print(x+y)         # the plus sign works
print()
print(np.add(x,y)) #so does the numpy function works "add"

[[322.1 324.1]
 [342.1 344. ]]

[[322.1 324.1]
 [342.1 344. ]]


Subtract:

In [69]:
print(x-y)              #the minus sign works
print()
print(np.subtract(x,y)) #o does the numpy function works "subtract"

[[-100.1 -100.1]
 [-100.1 -100. ]]

[[-100.1 -100.1]
 [-100.1 -100. ]]


Multiplication:

In [70]:
(x * y)                   #the multiple sign works
print()
print(np.multiply(x,y))   #so does the numpy function works "multiply"


[[23432.1 23755.2]
 [26753.1 27084. ]]


Division:

In [71]:
#divide
print(x / y)               #the divide sign woks           

print()
print(np.multiply(x,y))   #so does the numpy function works "divide"

[[0.52581715 0.52805281]
 [0.54726368 0.54954955]]

[[23432.1 23755.2]
 [26753.1 27084. ]]


Square root:

In [72]:
print(x ** y)             #the double multiple sign woks           

print()
print(np.multiply(x,y))   #so does the numpy function works "square root"

[[inf inf]
 [inf inf]]

[[23432.1 23755.2]
 [26753.1 27084. ]]


<ipython-input-72-c8f11e241a3f>:1: RuntimeWarning: overflow encountered in power
  print(x ** y)             #the double multiple sign woks


Exponential:

In [73]:
#exponential
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [74]:
#set up a random 2x5 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[ -1.12109214  -8.01638209  24.42433998   9.23961777  -1.05642766]
 [ -2.09490756 -11.33839268  -0.09328962 -14.05778245  -4.59139182]]


In [75]:
#compute the mean for all elements
print(arr.mean())

-0.8705708267460445


In [76]:
#compute the mean by row
print(arr.mean(axis = 1))

[ 4.69401117 -6.43515283]


In [77]:
#compute the mean by column
print(arr.mean(axis = 0))

[-1.60799985 -9.67738739 12.16552518 -2.40908234 -2.82390974]


In [78]:
#sum all the element
print(arr.sum())

-8.705708267460444


In [79]:
#compute the median
print(np.median(arr, axis = 1))

[-1.05642766 -4.59139182]


In [80]:
print(np.median(arr, axis = 0))

[-1.60799985 -9.67738739 12.16552518 -2.40908234 -2.82390974]


# Sorting:


In [81]:
#create 10 element array of random
unsorted = np . random.randn(10)
print(unsorted)

[ 0.07435178 -0.41714648  0.63314224 -1.94337753  0.0948744   0.45206731
  0.61317939 -0.03494129 -0.94717862  0.57380895]


In [82]:
# sorrt funt works to arrange ascending order
unsorted = np . random.randn(10,2)
print(unsorted)

[[ 1.50209168  0.86238292]
 [ 1.07083212 -1.65269504]
 [ 0.90204374  0.06736497]
 [-0.45457135 -0.17694734]
 [ 0.28178939  0.66905432]
 [ 0.69431025 -1.17250294]
 [-1.00318454 -0.10089647]
 [ 0.78324631  0.55146125]
 [ 0.98996985 -1.48665326]
 [-0.77774391  1.54459891]]


In [83]:
#create copy and sort
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)


[[ 0.86238292  1.50209168]
 [-1.65269504  1.07083212]
 [ 0.06736497  0.90204374]
 [-0.45457135 -0.17694734]
 [ 0.28178939  0.66905432]
 [-1.17250294  0.69431025]
 [-1.00318454 -0.10089647]
 [ 0.55146125  0.78324631]
 [-1.48665326  0.98996985]
 [-0.77774391  1.54459891]]

[[ 1.50209168  0.86238292]
 [ 1.07083212 -1.65269504]
 [ 0.90204374  0.06736497]
 [-0.45457135 -0.17694734]
 [ 0.28178939  0.66905432]
 [ 0.69431025 -1.17250294]
 [-1.00318454 -0.10089647]
 [ 0.78324631  0.55146125]
 [ 0.98996985 -1.48665326]
 [-0.77774391  1.54459891]]


In [84]:
#inplace sorting
print(unsorted)

[[ 1.50209168  0.86238292]
 [ 1.07083212 -1.65269504]
 [ 0.90204374  0.06736497]
 [-0.45457135 -0.17694734]
 [ 0.28178939  0.66905432]
 [ 0.69431025 -1.17250294]
 [-1.00318454 -0.10089647]
 [ 0.78324631  0.55146125]
 [ 0.98996985 -1.48665326]
 [-0.77774391  1.54459891]]


# Finding unique values:

In [85]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


Set operation with np.array datatype:

In [86]:
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'bulb', 'chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [87]:
#print common element
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [88]:
#Print each element without repeat
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [89]:
#element in s1 that are not in s2
print(np.setdiff1d(s1,s2))


['desk']


In [90]:
#which element of s1 is also in s2
print(np.in1d(s1,s2))

[False  True  True]


# Brodcasting:

In [91]:
import numpy as np
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [92]:
#creat a rank 1 nd array with 3 values
add_rows = np.array([1,0,2])
print(add_rows)

[1 0 2]


In [93]:
#add to each row of 'start' using broadcasting
y = start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [94]:
#creat an ndarray which is 4*1 to broadcasting across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [95]:
#add to each column of 'start' using broadcasting
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [96]:
#this will just broadcast in both dimensions
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Examples from the slides

In [97]:
#creat our 3*4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [98]:
#creat our 4*1 matrix
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [99]:
#add the two together using broadcasting
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


# Speesdtest: arrays vs list:

Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.



Speesdtest: arrays vs list

first step parameters for the speed test. we'll be testing time to sum elemnts in an ndarray versus a list

In [100]:
from numpy import arange
from timeit import Timer
size = 1000000
timeits = 1000

In [101]:
#creat the ndarray woth values 0,1,2,....,size-1
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [102]:
#time expects the operation as parameter
#here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")
print("Time taken by numpy ndarray: %f seconds" %
     (timer_numpy.timeit(timeits)/ timeits))

Time taken by numpy ndarray: 0.000542 seconds


In [103]:
#creat the list with values 0,1,2,....., size-1
a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [104]:
#timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")
print("Time taken by list: % f seconds" %
     (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.030517 seconds


Read or write disk:

In [105]:
import numpy as np

In [106]:
an_array = np.array([3,33,333]) 
print(type(an_array))

<class 'numpy.ndarray'>


# Binary Formate

In [107]:
#create one array
x = np.array([23.23, 24.24])

In [108]:
#save it in an_array
np.save('an_array', x)

In [109]:
#load it in an_array using numpy (.npy)
np.load('an_array.npy')

array([23.23, 24.24])

# Text Formate

In [110]:
np.savetxt('array.txt', X=x, delimiter=',')

In [111]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

Additional Common ndarray Operations


dot product on matrices and inner product on vectors

In [112]:
#determine the dot product of two matrices
x2d = np.array([[1,1],[2,2]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[4 4]
 [8 8]]

[[4 4]
 [8 8]]


In [113]:
#detremine the inner product of two vectors
a1d =np.array([9 , 9])
b1d =np.array([10,10])
print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))


180

180


In [114]:
#dot produce on an array and vectore  2d nd 1d
print(x2d.dot(a1d))
print()
print((np.dot(x2d, a1d)))

[18 36]

[18 36]


Sum:

In [115]:
#sum element in the array
ex1 = np.array([[11,12], [21,22]])
print(np.sum(ex1))      #add all members

66


In [116]:
print(np.sum(ex1, axis=0))   #column wise sum 
#axis=0 is for column

[32 34]


In [117]:
print(np.sum(ex1, axis=1))   #row wise
#axis=1 is for row

[23 43]


# Element wise function:

for ex let's compare two array values to get the maximum of each

In [118]:
#random array
x = np.random.randn(8)
x

array([-0.65356748, -0.1254826 , -0.41973212,  0.91605634, -1.0977258 ,
       -0.09510644, -0.95062383,  0.12650497])

In [119]:
#another random array
y = np.random.randn(8)
y

array([-1.37620526,  0.60926312, -0.91584785,  0.15667025,  0.52882227,
       -0.90208038, -1.6049025 ,  0.27592848])

In [120]:
#return element wise maximum btn two array
#written the maximum elements between two arrays
import numpy as np
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x, y)

array([ 0.59571617, -0.726783  , -0.72746783, -0.09277615,  0.08620863,
        0.73620457, -0.91387586,  0.68057473])

# Reshaping array:

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [121]:
#reshaping array
#grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [122]:
#reshape to be a 4*5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [123]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Transpose:

In [124]:
#transpose
#convert rows into columns and columns into rows
ex1 = np.array([[11,12], [21,22]])
ex1.T

array([[11, 21],
       [12, 22]])

Indexing using where():

In [125]:
#indexing using where()

x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [126]:
#for true element print from x_1 array
#for false element print from y_1 array

out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [127]:
out = np.where(filter, y_1, x_1)
print(out)

[11  2 33  4 55]


In [128]:

mat = np.random.randn(5,5)
mat


array([[ 1.16994731,  0.24351046, -1.49856546, -0.18128805, -0.1575042 ],
       [-0.78947801, -0.4035801 ,  1.43079289, -1.14726517, -1.40257066],
       [-0.48036893,  1.30412363, -0.40843325, -0.51020722,  1.117815  ],
       [ 0.720341  , -0.65381572,  0.54440923, -1.85077371, -0.7226153 ],
       [-0.65552102,  0.31647644,  0.54739664,  1.68860545,  0.38271905]])

In [173]:
np.where(mat> 0.5, 1000, -1)  

'''
if mat>0.5:
 replace(1000)
else:
 replace(-1)'''

array([[1000,   -1,   -1,   -1,   -1],
       [  -1,   -1, 1000,   -1,   -1],
       [  -1, 1000,   -1,   -1, 1000],
       [1000,   -1, 1000,   -1,   -1],
       [  -1,   -1, 1000, 1000,   -1]])

# "any" or "all" conditionals:

In [130]:
#"any" or "all" conditionals
arr_bools =np.array([True, False,True, True,False])

In [131]:
arr_bools.any()

True

In [132]:
arr_bools.all()

False

# Random number generation:

In [133]:
import numpy as np
Y = np.random.normal(size = (1,5))[0]
print(Y)

[-1.29846986  0.35095844  0.87572722  0.06835724 -1.61990436]


In [134]:
#giving the size to the matrix
Z = np.random.randint(low=2, high=50, size=4)
print(Z)

[46 30 42 20]


In [135]:
#Permutation shuffal the values from z and print
np.random.permutation(Z)     #return a new ordering of element in Z

array([30, 46, 20, 42])

In [136]:
np.random.uniform(size=4)    #uniform distribution 
                            #for curve

array([0.79501717, 0.35272592, 0.95858852, 0.55562005])

In [137]:
np.random.normal(size=4)    #normal distribution

array([ 1.65282689, -1.84077368,  0.36663206,  1.35273874])

# Merging Data Set:

In [138]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[ 3 38]
 [10 18]]

[[32 25]
 [25  8]]


In [139]:
np.vstack((K,M))  #merge according to column

array([[ 3, 38],
       [10, 18],
       [32, 25],
       [25,  8]])

In [140]:
np.hstack((K,M)) #merge acoording to rows

array([[ 3, 38, 32, 25],
       [10, 18, 25,  8]])

In [141]:
np.concatenate([K,M],axis = 0) #concatenate accordig to column

array([[ 3, 38],
       [10, 18],
       [32, 25],
       [25,  8]])

In [142]:
np.concatenate([K,M.T],axis =1)  #concatenate according to rows

array([[ 3, 38, 32, 25],
       [10, 18, 25,  8]])

# Practice:

In [143]:
import numpy

In [144]:
import numpy

arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [147]:
import numpy as np

print (np.__version__)

1.19.2


In [148]:
arr = numpy.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [150]:
#Use a tuple to create a NumPy array:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


In [151]:
#Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

42


In [152]:
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

#These are the most common and basic arrays.
#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [153]:
#An array that has 1-D arrays as its elements is called a 2-D array.

#These are often used to represent matrix or 2nd order tensors.
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [154]:
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
#These are often used to represent a 3rd order tensor.

#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [155]:
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
#check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [156]:
#An array can have any number of dimensions.
#When the array is created, you can define the number of dimensions by using the ndmin argument.

#Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [159]:
'''An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

Example
Create an array with 5 dimensions and verify that it has 5 dimensions:

'''
#Get the first element from the following array:

import numpy as np
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [160]:
#Get the second element from the following array.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [161]:
#Get third and fourth elements from the following array and add them.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])


7


In [162]:
#To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

#Access the 2nd element on 1st dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [163]:
#Access the 5th element on 2nd dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [164]:
#To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [165]:
#Use negative indexing to access an array from the end.

#Print the last element from the 2nd dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [166]:
#Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [167]:
#Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [168]:
#Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [169]:
#Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [170]:
#Return every other element from index 1 to index 5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [171]:
#Return every other element from the entire array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [172]:
#From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]
